target 'KeychainExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KeychainExample

 pod 'KeychainSwift', '~> 13.0'

  target 'KeychainExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end


end
